spring:
  application:
    name: spring-cloud-mall-eureka
server:
  port: 1001
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:1002/eureka